name: Transition multiple Jira issues
description: Find Jira issue keys from commit messages in pull requests and transition them
branding:
  icon: move
  color: blue
inputs:
  github-token:
    description: Your everyday GitHub token used for GitHub Actions
    required: true
  target-status:
    description: To which status the issues found in the pull request should transition to
    required: true
  pr-number:
    description: Pull Request number to get commits to find issue references
    required: true
  issue-prefixes:
    description: Comma separated list of the prefixes to scan
    required: true
  jira-project-key:
    description: Key of your Jira project
    required: true
  jira-base-url:
    description: URL of Jira instance
    required: true
  jira-api-token:
    description: Access Token for Authorization
    required: true
  jira-user-email:
    description: Email of the user for which Access Token was created for
    required: true
  do-transitions:
    description: Control the transitions
    required: false
    default: "true"
  release-version:
    description: Control the releasing current version
    required: false
    default: "false"
  ignore-statuses:
    description: Comma separated list of statuses to ignore
    required: false
    default: ""
runs:
  using: "node12"
  main: "./dist/index.js"
